Team-inglo/Giggle-Server

.github/workflows/dev-cicd.yml
closed #25 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- redis 연결을 위한 docker network 추가
N/A
=> 🌏 Deploy - redis 연결을 위한 docker network 추가

src/main/java/com/inglo/giggle/security/handler/login/DefaultLoginSuccessHandler.java
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 로그인 시 access token이 쿠키로 넘어가는 버그 수정
N/A
=> 🐞 BugFix - 로그인 시 access token이 쿠키로 넘어가는 버그

http/school/SchoolControllerHttpRequest.http, src/main/java/com/inglo/giggle/document/application/dto/response/ReadOwnerDocumentSummaryResponseDto.java, src/main/java/com/inglo/giggle/document/application/service/ReadOwnerDocumentSummaryService.java, src/main/java/com/inglo/giggle/resume/repository/mysql/EducationRepository.java, src/main/java/com/inglo/giggle/school/application/controller/query/SchoolUsersQueryV1Controller.java, src/main/java/com/inglo/giggle/school/application/dto/response/ReadSchoolBriefResponseDto.java, src/main/java/com/inglo/giggle/school/application/dto/response/ReadUserSchoolBriefResponseDto.java, src/main/java/com/inglo/giggle/school/application/dto/response/ReadUserSchoolDetailResponseDto.java, src/main/java/com/inglo/giggle/school/application/service/ReadSchoolBriefService.java, src/main/java/com/inglo/giggle/school/application/service/ReadUserSchoolBriefService.java, src/main/java/com/inglo/giggle/school/application/service/ReadUserSchoolDetailService.java, src/main/java/com/inglo/giggle/school/application/usecase/ReadSchoolBriefUseCase.java, src/main/java/com/inglo/giggle/school/application/usecase/ReadUserSchoolBriefUseCase.java, src/main/java/com/inglo/giggle/school/application/usecase/ReadUserSchoolDetailUseCase.java, src/main/java/com/inglo/giggle/school/domain/School.java, src/main/java/com/inglo/giggle/school/repository/mysql/SchoolRepository.java
closed #30 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- School 그룹(9번대 API) 구현
- 8.2 API ' (고용주) 서류 조회하기' 에 reason 반영하도록 변경
N/A
=> ✨ Feature - School 그룹(9번대 API) 구현

src/main/java/com/inglo/giggle/account/application/dto/request/UpdateUserRequestDto.java, src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java, src/main/java/com/inglo/giggle/account/domain/User.java, src/main/java/com/inglo/giggle/account/domain/service/UserService.java
closed #33 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 프로필 생일 수정 버그 해결
- 프로필 이미지 조회 버그 해결 
N/A
=> 🐞 BugFix - User 프로필 수정에서의 버그, 프로필 이미지 조회 버그 수정

http/posting/PostControllerHttpRequest.http, src/main/java/com/inglo/giggle/posting/application/controller/query/PostingUsersQueryV1Controller.java
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 6.4 엔드포인트 변경
N/A
=> 🐞 BugFix - 6.4 Invalid EndPoint Bug 해결

src/main/java/com/inglo/giggle/resume/application/dto/request/CreateUserWorkExperienceRequestDto.java, src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserWorkExperienceRequestDto.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserLanguageSummaryResponseDto.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java, src/main/java/com/inglo/giggle/resume/domain/WorkExperience.java
closed #40 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 7.1 Null값에 대한 처리
- 7.3 size 수정
- 7.4 오타수정
N/A
=> 🐞 BugFix - 7.1 Null값에 대한 처리 , 7.3 size 수정 , 7.4 오타수정

http/auth/AuthControllerHttpRequest.http, http/posting/PostControllerHttpRequest.http, src/main/java/com/inglo/giggle/posting/application/controller/query/PostingGuestsQueryV1Controller.java, src/main/java/com/inglo/giggle/posting/application/controller/query/PostingQueryV1Controller.java, src/main/java/com/inglo/giggle/posting/application/controller/query/PostingUsersQueryV1Controller.java, src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java, src/main/java/com/inglo/giggle/posting/application/usecase/ReadGuestJobPostingOverviewsUseCase.java, src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
closed #36 
어떤 변경사항이 있었나요?
- 검색 쿼리를 수정합니다.
N/A
N/A
=> 🐞 BugFix - 4.1 API Sorting Error

http/resume/ResumeControllerHttpRequest.http, src/main/java/com/inglo/giggle/resume/application/controller/command/ResumeUsersCommandV1Controller.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
closed #43 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 7.7 miss endpoint
- 7.1 null point exception
N/A
=> 🐞 BugFix - 7.7 miss endpoint, 7.1 null point exception

http/posting/PostControllerHttpRequest.http, src/main/java/com/inglo/giggle/posting/application/controller/query/PostingQueryV1Controller.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java, src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java, src/main/java/com/inglo/giggle/posting/application/usecase/ReadJobPostingOverviewUseCase.java, src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
closed #51 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- SQL 에러 해결
N/A
- 없습니다.
=> 🐞 BugFix - API_4.1, 4.3 Query Error

http/posting/PostControllerHttpRequest.http, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingDetailService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java, src/main/java/com/inglo/giggle/posting/domain/JobPosting.java, src/main/java/com/inglo/giggle/posting/repository/mysql/BookMarkRepository.java
closed #57 
어떤 변경사항이 있었나요?
-쿼리 에러 해결
N/A
=> 🐞 BugFix - Proxy Error

src/main/java/com/inglo/giggle/account/application/service/ReadUserSummaryService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadUserJobPostingBriefService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadUserJobPostingValidationService.java, src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeDetailService.java, src/main/java/com/inglo/giggle/resume/domain/service/EducationService.java, src/main/java/com/inglo/giggle/resume/repository/mysql/EducationRepository.java, src/main/java/com/inglo/giggle/school/application/service/ReadUserSchoolDetailService.java
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 7.1 NOT FOUND ERROR
- 7.7 Education SQL ERROR
=> 🐞 BugFix - 7.1 Resume NOT FOUND ERROR

http/posting/PostControllerHttpRequest.http, src/main/java/com/inglo/giggle/posting/application/controller/query/PostingOwnersQueryV1Controller.java, src/main/java/com/inglo/giggle/posting/application/controller/query/PostingUsersQueryV1Controller.java, src/main/java/com/inglo/giggle/posting/application/service/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsService.java, src/main/java/com/inglo/giggle/posting/application/usecase/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsUseCase.java, src/main/java/com/inglo/giggle/posting/repository/mysql/UserOwnerJobPostingRepository.java
closed #66 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
sorting을 추가했습니다. 
N/A
없습니다.
=> 🐞BugFix - API-4.6 (고용주) 공고에 대한 지원자 리스트 조회 수정

src/main/java/com/inglo/giggle/posting/application/controller/query/PostingOwnersQueryV1Controller.java, src/main/java/com/inglo/giggle/posting/application/service/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsService.java
closed #68 
어떤 변경사항이 있었나요?
Sorting nullable을 처리했습니다.
N/A
없습니다.
=> 🔨 Refactor - 4.6 API Sotring

src/main/java/com/inglo/giggle/posting/application/service/CreateOwnerJobPostingService.java, src/main/java/com/inglo/giggle/posting/application/service/UpdateOwnerJobPostingService.java
closed #72 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- API 4.10, 4.11 에서 NullpointError을 isBlank로 막습니다. 
N/A
없습니다.
=> 🔨 Refactor - 공고 등록 time값 수정 

src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java
closed #74 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
=> 🐞 BugFix - DeadLine Error 

src/main/java/com/inglo/giggle/core/constant/Constants.java, src/main/java/com/inglo/giggle/document/application/dto/response/ReadOwnerDocumentSummaryResponseDto.java, src/main/java/com/inglo/giggle/document/application/dto/response/ReadPartTimeEmploymentPermitDetailResponseDto.java, src/main/java/com/inglo/giggle/document/application/dto/response/ReadStandardLaborContractDetailResponseDto.java, src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java, src/main/java/com/inglo/giggle/document/application/service/CreateUserIntegratedApplicationService.java, src/main/java/com/inglo/giggle/document/application/service/ReadStandardLaborContractService.java, src/main/java/com/inglo/giggle/document/application/service/UpdateUserDocumentStatusSubmissionService.java, src/main/java/com/inglo/giggle/document/application/service/UpdateUserIntegratedApplicationService.java, src/main/java/com/inglo/giggle/document/domain/service/IntegratedApplicationService.java, src/main/java/com/inglo/giggle/document/domain/service/PartTimeEmploymentPermitService.java, src/main/java/com/inglo/giggle/document/domain/service/StandardLaborContractService.java
closed #76 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 서류 상세 조회 시, 고용주 작성 부분 null일 때의 처리 로직 추가
- 각 신청서 별 서명 사진 크기 조절
- 통합신청서 생성 시 파일이 바로 생성되도록 로직 변경
- 통합신청서 수정 시 파일이 바로 생성되도록 로직 변경
- 통합신청서 제출 로직 삭제
=> 🐞 BugFix - Null Point Exception + 서류 관련 로직 수정

src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
closed #81 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 🐞 BugFix - [QA#5] D+a 인 공고는 보여주지 않도록 수정하기
=> 🐞 BugFix - [QA#5] D+a 인 공고는 보여주지 않도록 수정하기

src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java, src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
closed #83 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 🐞 BugFix - today 파라미터 미전달 버그 수정
=> 🐞 BugFix - today 파라미터 미전달 버그 수정

http/posting/PostControllerHttpRequest.http, src/main/java/com/inglo/giggle/document/application/controller/query/DocumentOwnersQueryV1Controller.java, src/main/java/com/inglo/giggle/document/application/dto/response/ReadOwnerDocumentSummaryResponseDto.java, src/main/java/com/inglo/giggle/document/application/dto/response/ReadUserDocumentSummaryResponseDto.java, src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java, src/main/java/com/inglo/giggle/document/application/service/CreateUserIntegratedApplicationService.java, src/main/java/com/inglo/giggle/document/application/service/ReadOwnerDocumentSummaryService.java, src/main/java/com/inglo/giggle/document/application/service/UpdateUserIntegratedApplicationService.java, src/main/java/com/inglo/giggle/document/application/usecase/ReadOwnerDocumentSummaryUseCase.java, src/main/java/com/inglo/giggle/document/domain/service/DocumentService.java
closed #88 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 각 서류 워드파일만 제공으로 변경
N/A
=> 🔨 Refactor - 각 서류 워드파일만 제공으로 변경

http/auth/AuthControllerHttpRequest.http, http/term/TermControllerHttpRequest.http, src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultOwnerRequestDto.java, src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultUserRequestDto.java, src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultOwnerService.java, src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultUserService.java, src/main/java/com/inglo/giggle/term/application/controller/command/TermCommandV1Controller.java, src/main/java/com/inglo/giggle/term/application/controller/query/TermQueryV1Controller.java, src/main/java/com/inglo/giggle/term/application/dto/request/CreateTermAccountRequestDto.java, src/main/java/com/inglo/giggle/term/application/dto/response/ReadTermDetailResponseDto.java, src/main/java/com/inglo/giggle/term/application/service/CreateTermAccountService.java, src/main/java/com/inglo/giggle/term/application/service/ReadTermDetailService.java, src/main/java/com/inglo/giggle/term/application/usecase/CreateTermAccountUseCase.java, src/main/java/com/inglo/giggle/term/application/usecase/ReadTermDetailUseCase.java, src/main/java/com/inglo/giggle/term/domain/Term.java, src/main/java/com/inglo/giggle/term/domain/TermAccount.java, src/main/java/com/inglo/giggle/term/domain/service/TermAccountService.java, src/main/java/com/inglo/giggle/term/domain/type/ETermType.java, src/main/java/com/inglo/giggle/term/repository/mysql/TermAccountRepository.java, src/main/java/com/inglo/giggle/term/repository/mysql/TermRepository.java
closed #91 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 회원가입 시 약관 등록 과정 추가
- 종류별 약관 조회 API 구현
- 약관 등록 API 구현
N/A
=> ✨ Feature - 약관 조회 및 약관 동의 API 구현

src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java, src/main/java/com/inglo/giggle/document/repository/mysql/RejectRepository.java
closed #97 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 재검토 요청이 두 개 이상일때의 버그 수정
N/A
=> 🐞 BugFix: 재검토 요청이 두 개 이상일때의 버그 수정

src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java
closed #100 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 불필요 로깅 제거
N/A
=> 🔨 Refactor - 불필요 로깅 제거

src/main/java/com/inglo/giggle/core/constant/Constants.java
closed #102 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 11.1 약관 정보 상세 조회 Public으로 변경
N/A
=> 🔨 Refactor - 11.1 약관 정보 상세 조회 Public으로 변경

src/main/java/com/inglo/giggle/document/application/service/ConfirmUserDocumentService.java, src/main/java/com/inglo/giggle/document/application/service/ReadOwnerDocumentSummaryService.java, src/main/java/com/inglo/giggle/document/domain/Reject.java, src/main/java/com/inglo/giggle/document/repository/mysql/RejectRepository.java
closed #104 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- Reject에 AutoGenerated Id 추가
N/A
=> 🔨 Refactor - Reject에 AutoGenerated Id 추가

src/main/java/com/inglo/giggle/term/application/service/ReadTermDetailService.java, src/main/java/com/inglo/giggle/term/repository/mysql/TermRepository.java
closed #106 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
=> 🐞 BugFix - Term 조회 버그 해결

build.gradle, http/TestScenarioOne.http, http/TestScenarioOneEnd.http, http/TestScenarioTwo.http, http/auth/AuthControllerHttpRequest.http, src/main/java/com/inglo/giggle/address/domain/Address.java, src/main/java/com/inglo/giggle/document/domain/service/PartTimeEmploymentPermitService.java, src/main/java/com/inglo/giggle/document/domain/service/StandardLaborContractService.java
closed #112 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 시간제 취업 허가서 호환성 버그 해결
N/A
=> 🐞 BugFix - 시간제 취업 허가서 호환성 버그 해결

src/main/java/com/inglo/giggle/document/domain/service/PartTimeEmploymentPermitService.java
closed #114 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 시간제 취업허가서 서명 위치가 어긋나있는 버그 수정
N/A
=> 🐞 BugFix - 시간제 취업허가서 서명 위치가 어긋나있는 버그 수정

http/TestScenarioTwo.http, src/main/java/com/inglo/giggle/core/constant/Constants.java, src/main/java/com/inglo/giggle/document/application/service/UpdateUserIntegratedApplicationService.java, src/main/java/com/inglo/giggle/document/domain/service/IntegratedApplicationService.java, src/main/java/com/inglo/giggle/document/domain/service/PartTimeEmploymentPermitService.java
closed #116 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 통합 신청서 서명이 없어야 할 위치에도 존재하던 버그 수정
N/A
=> 🐞 BugFix - 통합 신청서 서명이 없어야 할 위치에도 존재하던 버그 수정

src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
closed #118 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 검색 쿼리 Distinct와 GroupBy의 혼용으로 인한 버그 수정
N/A
=> 🐞 BugFix - 검색 쿼리 Distinct와 GroupBy의 혼용으로 인한 버그 수정

http/auth/AuthControllerHttpRequest.http, src/main/java/com/inglo/giggle/security/application/controller/AuthController.java, src/main/java/com/inglo/giggle/security/application/dto/request/UpdateDeviceTokenRequestDto.java, src/main/java/com/inglo/giggle/security/application/service/UpdateDeviceTokenService.java, src/main/java/com/inglo/giggle/security/application/usecase/UpdateDeviceTokenUseCase.java, src/main/java/com/inglo/giggle/security/domain/mysql/Account.java, src/main/java/com/inglo/giggle/security/domain/service/AccountService.java
closed #120 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 디바이스 토큰 업데이트 API 구현
N/A
=> ✨ Feature - 디바이스 토큰 업데이트 API 구현

src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java
closed #121 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 3.1 유저 정보 조회에 주소 추가
N/A
=> ✨ Feature - 3.1 유저 정보 조회에 주소 추가

src/main/java/com/inglo/giggle/account/domain/User.java, src/main/java/com/inglo/giggle/address/domain/service/AddressService.java, src/main/java/com/inglo/giggle/security/application/controller/AuthController.java, src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultUserRequestDto.java, src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultUserService.java
closed #128 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 2.5 기본 유저 회원가입에 address, nationality, birth 값 optional로 변경
- DB 자체에 nullable 허용
N/A
=> 🔨 Fix - 2.5 기본 유저 회원가입에 address, nationality, birth 값 optional로 변경

src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java
closed #130 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 3.1 유저 프로필 조회하기에 address, nationality, birth 세 값 null 반환 허용
N/A
=> 🔨 Fix - 3.1 유저 프로필 조회하기에 address, nationality, birth 세 값 null 반환 허용

src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserSummaryResponseDto.java
closed #132 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 3.3 유저 요약 정보 조회하기 address, nationality, birth 세 값 null 반환 허용
N/A
=> 🔨 Fix - 3.3 유저 요약 정보 조회하기 address, nationality, birth 세 값 null 반환 허용

src/main/java/com/inglo/giggle/account/application/dto/request/UpdateUserRequestDto.java, src/main/java/com/inglo/giggle/account/domain/service/UserService.java
closed #134 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 3.5 프로필 수정하기에 address, nationality, birth 세 값 null 허용
N/A
=> 🔨 Fix - 3.5 프로필 수정하기에 address, nationality, birth 세 값 null 허용

src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
closed #136 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 7.1 이력서 조회하기에 address, nationality, birth 세 값 null 허용
N/A
=> 🔨 Fix - 7.1 이력서 조회하기에 address, nationality, birth 세 값 null 허용

README.md
closed #139 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- Update Readme
N/A
=> 📃 Docs - Update Readme

src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDto.java
closed #138 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 7.19 이력서 조회하기에 address, nationality, birth 세 값 null 허용
N/A
=> 🔨 Fix - 7.19 이력서 조회하기에 address, nationality, birth 세 값 null 허용

src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserJobPostingValidationResponseDto.java, src/main/java/com/inglo/giggle/posting/application/service/ReadUserJobPostingValidationService.java
closed #142 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 4.8 공고 지원자격 확인하기 항상 True 반환하도록 변경
N/A
=> 🔨 Fix - 4.8 공고 지원자격 확인하기 항상 True 반환하도록 변경

http/auth/AuthControllerHttpRequest.http, src/main/java/com/inglo/giggle/core/constant/Constants.java, src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java, src/main/java/com/inglo/giggle/security/application/controller/AuthController.java, src/main/java/com/inglo/giggle/security/application/dto/request/ChangePasswordRequestDto.java, src/main/java/com/inglo/giggle/security/application/service/ChangePasswordService.java, src/main/java/com/inglo/giggle/security/application/service/ReissueAuthenticationCodeService.java, src/main/java/com/inglo/giggle/security/application/service/ReissuePasswordService.java, src/main/java/com/inglo/giggle/security/application/usecase/ChangePasswordUseCase.java
closed #145 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 2.11 비밀번호 변경 API 구현
N/A
=> ✨ Feature - 2.11 비밀번호 변경 API 구현

src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDto.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
closed #147 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 7.1, 7.19 이력서 조회에 필드 추가
N/A
=> 🔨 Fix - 7.1, 7.19 이력서 조회에 필드 추가

src/main/java/com/inglo/giggle/core/utility/DateTimeUtil.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDto.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDto.java
closed #148 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 7.1, 7.19 이력서 조회에 필드 추가 
N/A
=> 🔨 Fix - 7.1, 7.19 이력서 조회 Birth 반환 형식 변경

src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultTemporaryRequestDto.java
closed #150 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 아이디와 이메일 통합
N/A
=> 🔨 Fix - 아이디와 이메일 통합

src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultTemporaryRequestDto.java, src/main/java/com/inglo/giggle/security/domain/mysql/Account.java
closed #150 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
🔨 Fix - serialId 길이제한 변경
N/A
=> 🔨 Fix - serialId 길이제한 변경

http/posting/PostControllerHttpRequest.http, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingOverviewsResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java, src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java, src/main/java/com/inglo/giggle/posting/domain/JobPosting.java, src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
closed #152 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- Main화변 변경으로 인한 공고 조회 시 데이터 추가
N/A
=> 🔨 Fix - Main화변 변경으로 인한 공고 조회 시 데이터 추가

http/posting/PostControllerHttpRequest.http, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingOverviewsResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java, src/main/java/com/inglo/giggle/posting/application/service/ReadGuestJobPostingOverviewsService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java, src/main/java/com/inglo/giggle/posting/domain/JobPosting.java, src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
closed #152 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- no proxy error 수정
N/A
=> 🔨 Fix - no proxy error 수정

.github/ISSUE_TEMPLATE/task_request.md
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 이슈 템플릿 안 올라가는 버그 수정
=> 📃 Docs : 이슈 템플릿 안 올라가는 버그 수정

Dockerfile, k8s/mysql.yaml, k8s/redis.yaml
closed #174
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 도커 파일의 베이스 이미지를 변경했습니다. (크램폴린)
- yml의 베이스 이미지를 변경했습니다.
N/A
N/A
=> 🔨Fix: Dockerfile, Yaml 베이스 이미지 변경  

http/auth/AuthControllerHttpRequest.http, src/main/java/com/inglo/giggle/core/utility/S3Util.java, src/main/java/com/inglo/giggle/security/application/controller/AuthController.java, src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultOwnerService.java, src/main/java/com/inglo/giggle/security/application/service/SignUpDefaultUserService.java, src/main/java/com/inglo/giggle/security/application/usecase/SignUpDefaultOwnerUseCase.java, src/main/java/com/inglo/giggle/security/application/usecase/SignUpDefaultUserUseCase.java
closed #181 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 2.5 유저 회원가입시 토큰 발급
- 2.6 고용주 회원가입시 토큰 발급
N/A
N/A
=> ✨ Feature: 2.5, 2.6 유저, 고용주 회원가입시 토큰 발급

src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java, src/main/java/com/inglo/giggle/posting/application/service/CreateUserJobPostingService.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java
closed #191 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 마감된 공고에 대한 지원 시 예외처리 추가
- 공고 검색 조회 시, 서버 시간 출력하는 로깅 추가(크램폴린 서버시간 확인 용)
- ErrorCode (마감된 공고 관련) 추가
N/A
=> 🔨 Fix - 마감된 공고에 대한 지원 시 예외처리 추가

src/main/java/com/inglo/giggle/core/utility/PasswordUtil.java, src/main/java/com/inglo/giggle/security/application/dto/request/ChangePasswordRequestDto.java, src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultTemporaryRequestDto.java
closed #194 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 회원가입 시 비밀번호 특수문자 Validation 변경
기존: !,@,#<$,%,^,&,* 
변경 후: ~,!,@,#,$,%,^,&,*,?
- 비밀번호 변경 시 비밀번호 특수문자 Validation 변경
위와 같음
- 임시 비밀번호 생성 시, 들어갈 수 있는 특수문자 종류 추가
~,? 추가
=> 🔨 Fix - 회원가입 시 비밀번호 특수문자 Validation 변경

src/main/java/com/inglo/giggle/core/config/WebMVCConfig.java, src/main/java/com/inglo/giggle/core/constant/Constants.java, src/main/java/com/inglo/giggle/core/interceptor/pre/HttpAccountIDInterceptor.java, src/main/java/com/inglo/giggle/security/config/SecurityConfig.java, src/main/java/com/inglo/giggle/security/filter/JsonWebTokenAuthenticationFilter.java
closed #200 
어떤 변경사항이 있었나요?
- 해당 사진은 인증이 필요없는 URL의 정규식들입니다. 
- 해당 사진은 USER, OWNER, ADMIN에 해당하는 URL의 정규식들입니다.
- 해당 사진은 각 권한들이 겹치는 URL의 정규식입니다.
- 사진과 같이 Security Config에서 확인할수 있으며, 모두 정규식 처리가 되어있습니다.
N/A
- 추가 API 생성시 Constants에 해당 URL을 작성해주시면 됩니다.
- ### 정규식에 들어가는 URL들은 겹처서는 안됩니다!!!!!
=> ♻️ Refactor: Security 권한 분리

src/main/java/com/inglo/giggle/core/config/WebMVCConfig.java, src/main/java/com/inglo/giggle/core/interceptor/pre/HttpAccountIDInterceptor.java
closed #207 
어떤 변경사항이 있었나요?
- 위의 사진과 같이 인증되지 않은 유저의 경우, anonymousUser이므로, 기존 null 체크에서 anonymousUser체크로 변경했습니다.
<br>
- 인증되지 않은 유저의 처리, 즉, public api의 경우에는 interceptor내부에서 처리하기때문에 excludePatterns를 삭제했습니다.
- excludePatterns의 경우, ANT-PATTERN으로 체크하기 때문에, 일반 정규식과는 맞지 않음 
N/A
N/A
=> 🔨Fix: Interceptor 로직 수정

.github/workflows/ci.yml, src/main/java/com/inglo/giggle/core/type/EVisa.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingOverviewsResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingOverviewResponseDto.java, src/main/resources/application-krampoline.yml
closed #209 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 비자 잘못된 배열로 가는 오류 수정
- 비자 종류 추가
N/A
ddl-auto create로 변경해두었습니다
=> 🔨 Fix - 비자 잘못된 배열로 가는 오류 수정 / 비자 종류 추가

k8s/api-server.yaml, src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingRepository.java
closed #211 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
<br>
###2. 배포를 위한 이미지 경로 수정
N/A
- 배포시 이미지 경로 수정하기
=> 🔨Fix: 공고 조회시 Lazy Loading 

src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingSummariesResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserOwnerJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsResponseDto.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingSummariesService.java
closed #213 
어떤 변경사항이 있었나요?
- 유저의 Nationality가 null인경우 null을 넘기게 처리했습니다.
- NotNull 어노테이션 제거 및 null 체크
<br>
N/A
N/A
=> 🔨 Fix: Nationality Null Check & 4.7 API ResponseDto 수정

k8s/api-server.yaml, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerJobPostingOverviewsResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingListResponseDto.java
closed #215 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 6.1 6.6 응답 데이터 변경
6.1, 6.6 모두에 company_name이 추가되었습니다.
N/A
크램폴린 이미지 경로가 변경되었습니다. 추후 반영할 것이 있을 때 참고해주세요
=> 🔨 Fix - 6.1 6.6 응답 데이터 변경

http/auth/AuthControllerHttpRequest.http, src/main/java/com/inglo/giggle/account/application/dto/request/UpdateOwnerRequestDto.java, src/main/java/com/inglo/giggle/account/application/dto/request/UpdateUserRequestDto.java, src/main/java/com/inglo/giggle/document/application/dto/request/CreateUserIntegratedApplicationRequestDto.java, src/main/java/com/inglo/giggle/document/application/dto/request/CreateUserStandardLaborContractRequestDto.java, src/main/java/com/inglo/giggle/document/application/dto/request/UpdateOwnerPartTimeEmploymentPermitRequestDto.java, src/main/java/com/inglo/giggle/document/application/dto/request/UpdateOwnerStandardLaborContractRequestDto.java, src/main/java/com/inglo/giggle/document/application/dto/request/UpdateUserIntegratedApplicationRequestDto.java, src/main/java/com/inglo/giggle/document/application/dto/request/UpdateUserStandardLaborContractRequestDto.java, src/main/java/com/inglo/giggle/notification/application/dto/ReadNotificationOverviewResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/request/CreateOwnerJobPostingRequestDto.java, src/main/java/com/inglo/giggle/posting/application/dto/request/UpdateOwnerJobPostingRequestDto.java, src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultOwnerRequestDto.java, src/main/java/com/inglo/giggle/security/application/dto/request/SignUpDefaultUserRequestDto.java
closed #217 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- RequestBody에 Valid가 제대로 적용되지 않는 문제 수정
위처럼 내부 DTO의 바깥에도 Valid를 걸어야 유효성 검사가 제대로 진행됨을 알 수 있었습니다.
N/A
=> 🔨 Fix - RequestBody에 Valid가 제대로 적용되지 않는 문제 수정

src/main/java/com/inglo/giggle/posting/application/dto/response/ReadGuestJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingDetailResponseDto.java
closed #220 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 공고 상세조회에 연령제한 필드 추가
N/A
=> 🔨 Fix - 공고 상세조회에 누락된 연령제한 필드 추가

src/main/java/com/inglo/giggle/account/application/dto/response/ReadUserDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadJobPostingSummariesResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserOwnerJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsResponseDto.java, src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingSummariesService.java, src/main/java/com/inglo/giggle/posting/application/service/UpdateOwnerJobPostingService.java, src/main/java/com/inglo/giggle/posting/domain/JobPosting.java
closed #219 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
N/A
N/A
=> 🔨Fix: 공고 수정시 Work Day Time 저장 안되는 문제

src/main/java/com/inglo/giggle/account/domain/Owner.java, src/main/java/com/inglo/giggle/account/domain/User.java, src/main/java/com/inglo/giggle/banner/domain/Banner.java, src/main/java/com/inglo/giggle/core/dto/BaseEntity.java, src/main/java/com/inglo/giggle/document/domain/ContractWorkDayTime.java, src/main/java/com/inglo/giggle/document/domain/Document.java, src/main/java/com/inglo/giggle/document/domain/IntegratedApplication.java, src/main/java/com/inglo/giggle/document/domain/PartTimeEmploymentPermit.java, src/main/java/com/inglo/giggle/document/domain/Reject.java, src/main/java/com/inglo/giggle/document/domain/StandardLaborContract.java, src/main/java/com/inglo/giggle/notification/domain/Notification.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserOwnerJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingListResponseDto.java, src/main/java/com/inglo/giggle/posting/domain/BookMark.java, src/main/java/com/inglo/giggle/posting/domain/CompanyImage.java, src/main/java/com/inglo/giggle/posting/domain/JobPosting.java, src/main/java/com/inglo/giggle/posting/domain/PostingWorkDayTime.java, src/main/java/com/inglo/giggle/posting/domain/UserOwnerJobPosting.java, src/main/java/com/inglo/giggle/resume/domain/AdditionalLanguage.java, src/main/java/com/inglo/giggle/resume/domain/Education.java, src/main/java/com/inglo/giggle/resume/domain/LanguageSkill.java, src/main/java/com/inglo/giggle/resume/domain/Resume.java, src/main/java/com/inglo/giggle/resume/domain/WorkExperience.java, src/main/java/com/inglo/giggle/school/domain/School.java, src/main/java/com/inglo/giggle/security/domain/mysql/Account.java, src/main/java/com/inglo/giggle/security/domain/mysql/AccountDevice.java, src/main/java/com/inglo/giggle/term/domain/Term.java, src/main/java/com/inglo/giggle/term/domain/TermAccount.java
closed #225 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- Soft Delete 적용
모든 테이블에 SoftDelete(논리적 삭제)를 구현했습니다. 기본적으로 SQLDelete를 통해 delete 메소드에 대해서 deleted_at 속성을 업데이트하도록 했으며, 상속을 받은 Entity에는 OnDelete 어노테이션을 통해 부모에 적용된 SQLDelete가 적용되어, Soft Delete가 가능하도록 했습니다.
abstract 클래스
부모를 상속받는 클래스
기본 클래스
- TermAccount에 지정되어있지 않은 테이블 명을 지정했습니다 -> term_accounts
N/A
=> ✨ Feature - Soft Delete 적용

src/main/java/com/inglo/giggle/address/dto/request/AddressRequestDto.java
closed #228 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 필수가 아닌 region4_depth를 Not Null로 유효성검사하고있던 에러를 수정합니다.
N/A
=> 🔨 Fix - region4_depth validation 오류 수정

k8s/api-server.yaml, src/main/java/com/inglo/giggle/core/event/dto/SendDiscordEventDto.java, src/main/java/com/inglo/giggle/core/event/listener/DiscordListener.java, src/main/java/com/inglo/giggle/core/exception/handler/ExceptionCatchHandler.java, src/main/java/com/inglo/giggle/core/exception/handler/HttpGlobalExceptionHandler.java, src/main/java/com/inglo/giggle/core/utility/HeaderUtil.java, src/main/java/com/inglo/giggle/core/utility/RestClientUtil.java, src/main/resources/application-krampoline.yml
closed #227 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 에러를 받는 리스너입니다.  
<br>
- 위와 같은 방식으로 구현되어있어 메세지를 처리합니다.
- 위의 사진과 같이 HttpGlobalExceptionHandler에서 잡히지 않는 서버의 치명적인 에러를 처리합니다.
N/A
- ‼️넘겨받은 application-yml을 수정하지 않으면 서버가 띄워지지 않습니다‼️
=> ✨ Feature: 디스코드 에러 웹훅 연결 구현

build.gradle, k8s/api-server.yaml, src/main/resources/application-krampoline.yml
closed #238 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- spring-boot-starter-actuator 의존성 추가
- application.yml에 아래를 추가하여, health check 엔드포인트 노출
- deployment.yaml에 readinessProbe 설정 추가
- 무중단 배포 테스트 -> 배포 이후에 테스트해보겠습니다.
배포되면 테스트 후 결과 말씀드리겠습니다!
=> ✨ Feature - 무중단 배포를 위한 의존성 추가 및 yaml에 설정 추가

src/main/java/com/inglo/giggle/core/exception/handler/HttpGlobalExceptionHandler.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnerUserJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingDetailResponseDto.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingListResponseDto.java, src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserSejongInstituteReqeustDto.java, src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserTopikReqeustDto.java
closed #249 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- updatedAt이 null인 경우 nullPointException 문제 해결
- 디스코드 알림 예외 제한
- 토픽, 세종학당 6레벨까지로 확장
=> 🔨 Fix - updatedAt이 null인 경우 nullPointException 문제 해결

src/main/java/com/inglo/giggle/posting/application/service/ReadJobPostingOverviewService.java, src/main/java/com/inglo/giggle/posting/repository/JobPostingRepository.java, src/main/java/com/inglo/giggle/posting/repository/impl/JobPostingRepositoryImpl.java, src/main/java/com/inglo/giggle/posting/repository/mysql/JobPostingJpaRepository.java
closed #253 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 공고 검색시 accountId를 추가했습니다.
<br>
- 오타를 수정했습니다.
- 전체 테스트
N/A
=> 🔨Fix: 공고 검색시 북마크가 전체 조회되는 이슈

src/main/java/com/inglo/giggle/core/utility/S3Util.java
closed #255 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 위와같이 URL 인코딩을 진행해서 S3에 업로드 됩니다.
N/A
N/A
=> 🔨 Fix: 파일 수정시 Url Encoding 

http/account/AccountControllerHttpRequest.http, src/main/java/com/inglo/giggle/document/application/service/CreateUserIntegratedApplicationService.java, src/main/java/com/inglo/giggle/document/application/service/CreateUserPartTimeEmploymentPermitService.java, src/main/java/com/inglo/giggle/document/application/service/CreateUserStandardLaborContractService.java
closed #257 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 서류 생성 시, 이미 존재하는 서류에 대한 예외처리 기능 추가
N/A
이거 도메인 서비스로 빼는게 좋을까요? 리펙토링하면 도메인서비스라는거 자체가 없어질 것 같아서 어떤식으로 구현해야할지 고민되네요
=> ✨ Feature - 서류 생성 시, 이미 존재하는 서류에 대한 예외처리 기능 추가

src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java, src/main/java/com/inglo/giggle/resume/application/dto/request/CreateUserEducationRequestDto.java, src/main/java/com/inglo/giggle/resume/application/dto/request/CreateUserWorkExperienceRequestDto.java, src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserEducationRequestDto.java, src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserWorkExperienceRequestDto.java, src/main/java/com/inglo/giggle/resume/controller/command/ResumeUsersCommandV1Controller.java
closed #259 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 위의 사진과 같이 날짜에 대한 Validation을 추가했습니다.
<br>
- 위의 사진과 같이 날짜에 대한 Validation을 추가했습니다.
N/A
- 위의 사진과 같이 execute로 넘기면서 `validate()`를 호출하면 됩니다.
=> 🔨 Fix: Education & WorkExperience 생성 및 수정 Validation 추가

src/main/java/com/inglo/giggle/security/application/dto/request/UpdateDeviceTokenRequestDto.java, src/main/java/com/inglo/giggle/security/application/service/UpdateDeviceTokenService.java
closed #261 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- deviceId를 String에서 UUID로 변경했습니다.
<br>
- 넘겨받은 deviceId를 그대로 사용합니다.
- 로그아웃 시 AccountDevice삭제
- `로그아웃 시 AccountDevice삭제` 는 다음 이슈에 업로드할 예정입니다.
=> 🔨 Fix: DeviceToken 생성 및 업데이트 DTO, 로직 수정

src/main/java/com/inglo/giggle/security/application/service/LogoutService.java, src/main/java/com/inglo/giggle/security/repository/AccountDeviceRepository.java, src/main/java/com/inglo/giggle/security/repository/impl/AccountDeviceRepositoryImpl.java, src/main/java/com/inglo/giggle/security/repository/mysql/AccountDeviceJpaRepository.java
closed #263 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 로그아웃 시 AccountDevice를 전체 삭제하는 로직을 추가했습니다.
N/A
N/A
=> 🔨 Fix: 로그아웃 시 AccountDevice 삭제 추가

src/main/java/com/inglo/giggle/resume/domain/WorkExperience.java
closed #265 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- WorkExperience 삭제 구문 오타 수정
N/A
=> 🔨 Fix - WorkExperience 삭제 구문 오타 수정

src/main/java/com/inglo/giggle/core/constant/Constants.java
closed #267 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
<br>
N/A
N/A
=> ✨ Feature: Admin 관련 API Security 적용

src/main/java/com/inglo/giggle/security/application/service/ReissueJsonWebTokenService.java, src/main/java/com/inglo/giggle/security/repository/RefreshTokenRepository.java, src/main/java/com/inglo/giggle/security/repository/impl/RefreshTokenRepositoryImpl.java, src/main/java/com/inglo/giggle/security/repository/redis/RefreshTokenRedisRepository.java
closed #269 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 다음과 같이 Token Validation을 추가했습니다.
N/A
N/A
=> 🔨 Fix: Reissue Token 로직 수정

http/auth/AuthControllerHttpRequest.http, http/posting/PostControllerHttpRequest.http, http/version/VersionControllerHttpRequest.http, src/main/java/com/inglo/giggle/core/constant/Constants.java, src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java, src/main/java/com/inglo/giggle/version/application/dto/response/ReadRecentVersionResponseDto.java, src/main/java/com/inglo/giggle/version/application/service/ReadRecentVersionService.java, src/main/java/com/inglo/giggle/version/application/usecase/ReadRecentVersionUseCase.java, src/main/java/com/inglo/giggle/version/controller/query/VersionQueryV1Controller.java, src/main/java/com/inglo/giggle/version/domain/Version.java, src/main/java/com/inglo/giggle/version/domain/type/EOsType.java, src/main/java/com/inglo/giggle/version/repository/VersionRepository.java, src/main/java/com/inglo/giggle/version/repository/impl/VersionRepositoryImpl.java, src/main/java/com/inglo/giggle/version/repository/mysql/VersionJpaRepository.java
closed #273 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- Default value는 Ios로 기준을 잡았습니다.
N/A
N/A
=> ✨ Feature: Version 도메인 세팅 및 0.1 최신 버전 조회하기 API 구현

src/main/java/com/inglo/giggle/posting/application/dto/response/ReadUserUserOwnerJobPostingDetailResponseDto.java
closed #276 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 6.2 필드 변경
N/A
=> 🔨 Fix : 6.2 지원상태 조회하기 필드 변경

.github/workflows/dev-cicd.yml, .github/workflows/prod-cicd.yml
closed #285 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
=> 🌏 Deploy - firebase-key.json 볼륨마운트

http/resume/ResumeControllerHttpRequest.http, src/main/java/com/inglo/giggle/core/exception/error/ErrorCode.java, src/main/java/com/inglo/giggle/posting/domain/type/EJobCategory.java, src/main/java/com/inglo/giggle/resume/application/dto/request/CreateUserWorkPreferenceRequestDto.java, src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserWorkPreferenceRequestDto.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadAdminResumeDetailResponseDtoV2.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailResponseDtoV2.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDtoV2.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserWorkPreferenceDetailResponseDto.java, src/main/java/com/inglo/giggle/resume/application/service/CreateUserWorkPreferenceService.java, src/main/java/com/inglo/giggle/resume/application/service/DeleteUserWorkPreferenceService.java, src/main/java/com/inglo/giggle/resume/application/service/ReadAdminResumeDetailService.java, src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeDetailService.java, src/main/java/com/inglo/giggle/resume/application/service/ReadUserResumeDetailService.java, src/main/java/com/inglo/giggle/resume/application/service/ReadUserWorkPreferenceDetailService.java, src/main/java/com/inglo/giggle/resume/application/service/UpdateUserWorkPreferenceService.java, src/main/java/com/inglo/giggle/resume/application/usecase/CreateUserWorkPreferenceUseCase.java, src/main/java/com/inglo/giggle/resume/application/usecase/DeleteUserWorkPreferenceUseCase.java, src/main/java/com/inglo/giggle/resume/application/usecase/ReadUserWorkPreferenceDetailUseCase.java, src/main/java/com/inglo/giggle/resume/application/usecase/UpdateUserWorkPreferenceUseCase.java, src/main/java/com/inglo/giggle/resume/controller/command/ResumeUsersCommandV1Controller.java, src/main/java/com/inglo/giggle/resume/controller/query/ResumeUsersQueryV1Controller.java, src/main/java/com/inglo/giggle/resume/domain/Resume.java, src/main/java/com/inglo/giggle/resume/domain/WorkPreference.java, src/main/java/com/inglo/giggle/resume/repository/WorkPreferenceRepository.java, src/main/java/com/inglo/giggle/resume/repository/impl/WorkPreferenceRepositoryImpl.java, src/main/java/com/inglo/giggle/resume/repository/mysql/WorkPreferenceJpaRepository.java
closed #291 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 7.1, 7.19, 7.20 API에 희망근로조건 필드 work_preferences 배열 추가
- 7.21 유학생 희망 근로 조건 상세 조회 API 구현
- 7.22 유학생 희망 근로 조건 생성 API 구현
- 7.23 유학생 희망 근로 조건 수정 API 구현
- 7.24 유학생 희망 근로 조건 삭제 API 구현
- API 테스트
=> ✨ Feature - 희망근로조건 기능 추가

http/auth/AuthControllerHttpRequest.http, src/main/java/com/inglo/giggle/core/event/listener/EmailListener.java, src/main/java/com/inglo/giggle/core/utility/MailUtil.java
closed #288 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 메일 형식 변경
- 메일 보내는 방식 SMTP로 변경
N/A
=> ♻️ Refactor: 메일 형식 변경 및 메일 전송 방식 SMTP로 변경

http/resume/ResumeControllerHttpRequest.http, src/main/java/com/inglo/giggle/career/application/service/ReadGuestCareersOverviewsService.java, src/main/java/com/inglo/giggle/career/application/service/ReadUserCareersOverviewsService.java
closed #299 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 커리어 조회 시 sorting value TRENDING -> POPULAR 변경
N/A
=> 🔨 Fix: 커리어 조회 시 sorting value TRENDING -> POPULAR 변경

http/resume/ResumeControllerHttpRequest.http, src/main/java/com/inglo/giggle/career/application/service/ReadGuestCareersOverviewsService.java, src/main/java/com/inglo/giggle/career/application/service/ReadUserCareersOverviewsService.java
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
=> 🚀 Deploy : Dev -> Main

src/main/java/com/inglo/giggle/career/application/service/ReadGuestsCareersDetailsService.java, src/main/java/com/inglo/giggle/career/application/service/ReadUsersCareersDetailsService.java, src/main/java/com/inglo/giggle/career/repository/impl/CareerRepositoryImpl.java
closed #302 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 기존에는 career.getVisa로 가져왔으나 위와 같이 자바 컬랙션에 넘겨서 조회하게 했습니다.
N/A 
N/A
=> 🔨 Fix: Career 조회 시 Visa Lazy Loading 해결

src/main/java/com/inglo/giggle/career/application/service/ReadGuestsCareersDetailsService.java, src/main/java/com/inglo/giggle/career/application/service/ReadUsersCareersDetailsService.java
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
=> 🔨 Fix: Career 조회 시 Visa Lazy Loading 해결 (#303)

src/main/java/com/inglo/giggle/career/application/dto/request/CreateAdminsCareerRequestDto.java, src/main/java/com/inglo/giggle/posting/domain/type/EJobCategory.java
closed #305 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
N/A
N/A
=> 🔨  Fix: EJobCategory 수정

src/main/java/com/inglo/giggle/career/application/dto/request/CreateAdminsCareerRequestDto.java, src/main/java/com/inglo/giggle/posting/domain/type/EJobCategory.java
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
=> 🚀 Deploy : Dev -> Main 

src/main/java/com/inglo/giggle/resume/domain/BookMarkResume.java, src/main/java/com/inglo/giggle/resume/domain/Resume.java, src/main/java/com/inglo/giggle/resume/repository/BookMarkResumeRepository.java, src/main/java/com/inglo/giggle/resume/repository/impl/BookMarkResumeRepositoryImpl.java, src/main/java/com/inglo/giggle/resume/repository/mysql/BookMarkResumeJpaRepository.java
closed #308 
어떤 변경사항이 있었나요?
<br>
N/A
N/A
=> ✨ Feature: 이력서 공개/비공개 컬럼 추가 및 이력서 북마크 도메인 추가

http/auth/AuthControllerHttpRequest.http, http/resume/ResumeControllerHttpRequest.http, src/main/java/com/inglo/giggle/resume/application/dto/request/UpdateUserResumeIsPublicRequestDto.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDtoV1.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadUserResumeDetailResponseDtoV2.java, src/main/java/com/inglo/giggle/resume/application/dto/response/UpdateOwnerResumeBookMarkResumeResponseDto.java, src/main/java/com/inglo/giggle/resume/application/dto/response/UpdateUserResumeIsPublicResponseDto.java, src/main/java/com/inglo/giggle/resume/application/service/UpdateOwnerResumeBookMarkResumeService.java, src/main/java/com/inglo/giggle/resume/application/service/UpdateUserResumeIsPublicService.java, src/main/java/com/inglo/giggle/resume/application/usecase/UpdateOwnerResumeBookMarkResumeUseCase.java, src/main/java/com/inglo/giggle/resume/application/usecase/UpdateUserResumeIsPublicUseCase.java, src/main/java/com/inglo/giggle/resume/controller/command/ResumeOwnersCommandV1Controller.java, src/main/java/com/inglo/giggle/resume/controller/command/ResumeUsersCommandV1Controller.java, src/main/java/com/inglo/giggle/resume/domain/BookMarkResume.java, src/main/java/com/inglo/giggle/resume/repository/BookMarkResumeRepository.java, src/main/java/com/inglo/giggle/resume/repository/impl/BookMarkResumeRepositoryImpl.java, src/main/java/com/inglo/giggle/resume/repository/mysql/BookMarkResumeJpaRepository.java
closed #310 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- v1, v2 모두 추가
N/A
N/A
=> ✨ Feature: 7.1 API 수정 및 7.23, 15.1 API 생성

http/resume/ResumeControllerHttpRequest.http, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailByResumeIdResponseDto.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeOverviewResponseDto.java, src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeDetailService.java, src/main/java/com/inglo/giggle/resume/application/usecase/ReadOwnerResumeDetailUseCase.java, src/main/java/com/inglo/giggle/resume/controller/query/ResumeOwnersQueryV1Controller.java, src/main/java/com/inglo/giggle/resume/repository/ResumeRepository.java, src/main/java/com/inglo/giggle/resume/repository/impl/ResumeRepositoryImpl.java, src/main/java/com/inglo/giggle/resume/repository/mysql/ResumeJpaRepository.java
closed #314 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- JobCategory LazyLoading 문제 해결 + 북마크 여부 필드 추가
=> 🔨 Fix - JobCategory LazyLoading 문제 해결 + 북마크 여부 필드 추가

http/auth/AuthControllerHttpRequest.http, http/resume/ResumeControllerHttpRequest.http, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeDetailByResumeIdResponseDto.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeOverviewResponseDto.java, src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeOverviewService.java, src/main/java/com/inglo/giggle/resume/application/usecase/ReadOwnerResumeOverviewUseCase.java, src/main/java/com/inglo/giggle/resume/controller/query/ResumeOwnersQueryV1Controller.java, src/main/java/com/inglo/giggle/resume/repository/ResumeRepository.java, src/main/java/com/inglo/giggle/resume/repository/impl/ResumeRepositoryImpl.java
closed #316 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 7.24 응답 필드에 address 추가. 유저의 "address.addressName" 에서 가져옵니다. null일 시 "지역 미등록" 으로 반환합니다.
- 북마크한 인재를 조회하기 위한 쿼리변수 "is-book-marked"를 추가했습니다.
N/A
=> 🔨 Fix - 7.24 address 필드 추가 및 query param: is-book-marked 추가

http/career/CarrerControllerHttpRequest.http, src/main/java/com/inglo/giggle/career/application/dto/request/UpdateAdminsCareerRequestDto.java, src/main/java/com/inglo/giggle/career/application/dto/response/ReadAdminsCareersDetailsResponseDto.java, src/main/java/com/inglo/giggle/career/application/dto/response/ReadAdminsCareersOverviewsResponseDto.java, src/main/java/com/inglo/giggle/career/application/service/CreateAdminsCareerService.java, src/main/java/com/inglo/giggle/career/application/service/DeleteAdminsCareerService.java, src/main/java/com/inglo/giggle/career/application/service/ReadAdminsCareersDetailsService.java, src/main/java/com/inglo/giggle/career/application/service/ReadAdminsCareersOverviewsService.java, src/main/java/com/inglo/giggle/career/application/service/UpdateAdminsCareerService.java, src/main/java/com/inglo/giggle/career/application/usecase/DeleteAdminsCareerUseCase.java, src/main/java/com/inglo/giggle/career/application/usecase/ReadAdminsCareersDetailsUseCase.java, src/main/java/com/inglo/giggle/career/application/usecase/ReadAdminsCareersOverviewsUseCase.java, src/main/java/com/inglo/giggle/career/application/usecase/UpdateAdminsCareerUseCase.java, src/main/java/com/inglo/giggle/career/controller/command/CareerAdminsCommandV1Controller.java, src/main/java/com/inglo/giggle/career/controller/query/CareerAdminQueryV1Controller.java, src/main/java/com/inglo/giggle/career/domain/Career.java, src/main/java/com/inglo/giggle/career/domain/CareerImage.java, src/main/java/com/inglo/giggle/career/repository/CareerImageRepository.java, src/main/java/com/inglo/giggle/career/repository/CareerRepository.java, src/main/java/com/inglo/giggle/career/repository/impl/CareerImageRepositoryImpl.java, src/main/java/com/inglo/giggle/career/repository/impl/CareerRepositoryImpl.java, src/main/java/com/inglo/giggle/career/repository/mysql/CareerImageJpaRepository.java, src/main/java/com/inglo/giggle/posting/application/dto/response/ReadOwnersJobPostingUserOwnerJobPostingUserOverviewsResponseDto.java, src/main/java/com/inglo/giggle/posting/application/service/UpdateOwnerJobPostingService.java
closed #319 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 구현 과정 속에서 image에 해당하는 SerialId가 필요했기에 사진과 같이 컬럼을 추가했습니다.
- 해당 컬럼은 이미 데이터베이스에 적용되어있습니다.
N/A
N/A
=> ✨ Feature: 어드민 커리어 API 구현 및 4.6 API DTO 수정

http/career/CarrerControllerHttpRequest.http, src/main/java/com/inglo/giggle/career/domain/Career.java, src/main/java/com/inglo/giggle/career/domain/CareerImage.java, src/main/java/com/inglo/giggle/posting/domain/CompanyImage.java
closed #322 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
columnDefinition = "TEXT" 을 명시해주지 않으면, mysql에 TINYTEXT로 속성이 부여되어, 긴 내용의 문자를 받지 못하는 버그 발생.
Lob 어노테이션 붙은 컬럼들 속성 TEXT로 변경
- Carrer -> detail
- CarrerImage -> imgUrl
- CompanyImage -> imgUrl
N/A
CarrerHttpRequest에 {{host_url}} 전부 넣어두었습니다. 기존 localhost:8080 -> host_url 변경
=> 🔨 Fix - Lob 어노테이션 붙은 컬럼들 속성 TEXT로 변경

src/main/java/com/inglo/giggle/core/type/ENationality.java
closed #327 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- ENationality가 Blank 인 경우 처리
N/A
=> 🔨 Fix - ENationality가 Blank 인 경우 처리

http/resume/ResumeControllerHttpRequest.http, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeOverviewResponseDto.java, src/main/java/com/inglo/giggle/resume/application/service/ReadOwnerResumeOverviewService.java, src/main/java/com/inglo/giggle/resume/repository/BookMarkResumeRepository.java, src/main/java/com/inglo/giggle/resume/repository/impl/BookMarkResumeRepositoryImpl.java, src/main/java/com/inglo/giggle/resume/repository/mysql/BookMarkResumeJpaRepository.java
closed #336 
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- isBookmarked가 true인 경우 무조건 true가 넘어가야하기때문에 로직을 수정했습니다.
N/A
N/A
=> 🔨 Fix: 7.24 API 메모리 오버로드 및 Dto 수정

src/main/java/com/inglo/giggle/career/domain/type/ECareerCategory.java, src/main/java/com/inglo/giggle/resume/application/dto/response/ReadOwnerResumeOverviewResponseDto.java
어떤 변경사항이 있었나요?
작업 내용을 작성해주세요.
- 작업 내용
=> 🌎 Deploy: ECareerCategory 추가
